version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: postgres-db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      TZ: ${POSTGRES_TZ}
      PGTZ: ${POSTGRES_PGTZ}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - ${POSTGRES_DATA_PATH}:/var/lib/postgresql/data
    networks:
      - internal-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $POSTGRES_USER -d $POSTGRES_DB" ]
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    ports:
      - "${PGADMIN_PORT}:80"
    depends_on:
      - postgres
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - internal-network

  patient-service:
    build:
      context: .
      dockerfile: Dockerfile
    image: patient-service:latest  # â† Name for the built image
    container_name: patient-service
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/${POSTGRES_DB}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      SPRING_JPA_HIBERNATE_DDL_AUTO: ${HIBERNATE_DDL_AUTO}
      SPRING_JPA_SHOW_SQL: ${SHOW_SQL}

      BILLING_SERVICE_ADDRESS_LOCALHOST: billing-service
      BILLING_SERVICE_GRPC_PORT: 9001

      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092


#    ports:not exposing for open
#      - "${APP_PORT}:4000"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - internal-network

  billing-service:
    build:
      context: ../billing-service
      dockerfile: Dockerfile
    image: billing-service:latest
    container_name: billing-service
    ports:
      - "4001:4001"
      - "9001:9001"
    networks:
      - internal-network

  analytics-service:
    build:
      context: ../analytics-service
      dockerfile: Dockerfile
    image: analytics-service:latest
    container_name: analytics-service
    ports:
      - "4003:4003"
    environment:
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    networks:
        - internal-network


  kafka:
    image: confluentinc/cp-kafka:7.6.1
    ports:
      - "${KAFKA_EXTERNAL_PORT}:${KAFKA_EXTERNAL_PORT}"
    environment:
      # KRaft mode
      KAFKA_NODE_ID: ${KAFKA_NODE_ID}
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_QUORUM_VOTERS: ${KAFKA_NODE_ID}@kafka:${KAFKA_CONTROLLER_PORT}
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      CLUSTER_ID: ${CLUSTER_ID}

      # Listeners
      KAFKA_LISTENERS: >
        PLAINTEXT://${KAFKA_INTERNAL_HOST}:${KAFKA_INTERNAL_PORT},
        CONTROLLER://${KAFKA_INTERNAL_HOST}:${KAFKA_CONTROLLER_PORT},
        EXTERNAL://0.0.0.0:${KAFKA_EXTERNAL_PORT}

      KAFKA_ADVERTISED_LISTENERS: >
        PLAINTEXT://${KAFKA_INTERNAL_HOST}:${KAFKA_INTERNAL_PORT},
        EXTERNAL://${KAFKA_EXTERNAL_HOST}:${KAFKA_EXTERNAL_PORT}

      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: >
        PLAINTEXT:PLAINTEXT,
        CONTROLLER:PLAINTEXT,
        EXTERNAL:PLAINTEXT

      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT

      # Dev-friendly settings
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0

    volumes:
      - ${KAFKA_DATAPATH}:/var/lib/kafka/data

    networks:
      - internal-network

  api-gateway:
    build:
      context: ../api-gateway
      dockerfile: Dockerfile
    image: api-gateway:latest
    container_name: api-gateway
    ports:
      - "4005:4005"
#    environment:
#      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    networks:
      - internal-network

  auth-service:
    build:
      context: ../auth-service
      dockerfile: Dockerfile
    image: auth-service:latest
    container_name: auth-service
    ports:
      - "4004:4004"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-auth:5432/auth_service
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      SPRING_JPA_HIBERNATE_DDL_AUTO: ${HIBERNATE_DDL_AUTO}
      SPRING_JPA_SHOW_SQL: ${SHOW_SQL}
      JWT_SECRET: 6KF7giFOBFp3exZhBihg9CR3iD1trEN8t7TgfECUKw6
      SPRING_JPA_DEFER_DATASOURCE_INITIALIZATION: true
      SPRING_SQL_INIT_MODE: always

    networks:
      - internal-network

  postgres-auth:
    image: postgres:16
    container_name: auth-service-db
    environment:
      POSTGRES_DB: auth_service
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      TZ: ${POSTGRES_TZ}
      PGTZ: ${POSTGRES_PGTZ}
    ports:
      - "5433:5432"
    volumes:
      - D:/Project2/PMS/patient-management/patient-service/authdata:/var/lib/postgresql/data
    networks:
      - internal-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $POSTGRES_USER -d auth_service" ]
      interval: 10s
      timeout: 5s
      retries: 5



networks:
  internal-network:
    driver: bridge

volumes:
  pgadmin_data:
  kafka_data:

